### ISSUE TITLE
Contrast ratio issue for content not contained within a panel pane

### ISSUE THREAD

**Issue by adamdelaney** [ITS-UofIowa/hawktools.uiowa.edu#9]
The default color or background color should be updated for pages that are not panelized or content not contained with in panels markup. For example: login page or user page.
<img width="580" alt="screen shot 2018-05-14 at 10 17 28 am" src="https://user-images.githubusercontent.com/1016880/40006534-44f0eebc-5760-11e8-811c-26e519db9431.png">
<img width="955" alt="screen shot 2018-05-14 at 10 17 04 am" src="https://user-images.githubusercontent.com/1016880/40006535-45006b1c-5760-11e8-8537-2df96e0af0e2.png">

**Comment by GaryRidgway** [comment]
This has been completed
